[package]
name = "kriyaetive"
version = "0.1.0"
edition = "2021"
authors = ["Sridhar Ananthakrishnan <sridhar<@>kriyaetive[.]org"]

[workspace]
members = ["draw"]

[dependencies]
env_logger = "0.11.3"
log = "0.4.21"
wasm-bindgen = "0.2.92"
wgpu = "0.20.0"
